// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateCargoTypeData, CreateCargoTypeErrors, CreateCargoTypeResponses, CreateClientData, CreateClientErrors, CreateClientResponses, CreateQuotationData, CreateQuotationErrors, CreateQuotationResponses, DownloadQuotationPdfData, DownloadQuotationPdfErrors, DownloadQuotationPdfResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetQuotationConfigData, GetQuotationConfigErrors, GetQuotationConfigResponses, GetQuotationData, GetQuotationErrors, GetQuotationResponses, ListCargoTypesData, ListCargoTypesErrors, ListCargoTypesResponses, ListClientsData, ListClientsErrors, ListClientsResponses, ListCurrenciesData, ListCurrenciesResponses, ListPaymentTermsData, ListPaymentTermsResponses, ListQuotationsData, ListQuotationsErrors, ListQuotationServiceTypesData, ListQuotationServiceTypesResponses, ListQuotationsResponses, LoginData, LoginErrors, LoginResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Iniciar sesión
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Renovar token de acceso
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Cambiar contraseña del usuario actual
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/change-password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Obtener datos del usuario autenticado
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

/**
 * Buscar tipos de carga (paginado por volumen)
 *
 * Listado paginado de tipos de carga. Filtra por substring case-insensitive
 * en `name` cuando se envía `q` (ILIKE acelerado por GIN trgm).
 * Default sort: `name ASC`. Cuando hay `q`, ranking primario por
 * `similarity(name, q) DESC`, tiebreak `name ASC`.
 * Para no filtrar, OMITIR el parámetro `q` (no enviarlo vacío).
 * Un `isActive` no booleano se interpreta como `false` (binder de JAX-RS).
 *
 */
export const listCargoTypes = <ThrowOnError extends boolean = false>(options?: Options<ListCargoTypesData, ThrowOnError>) => (options?.client ?? client).get<ListCargoTypesResponses, ListCargoTypesErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cargo-types',
    ...options
});

/**
 * Crear tipo de carga al vuelo
 *
 * Crea un tipo de carga al vuelo desde el wizard de cotizaciones. El `name`
 * se almacena en mayúsculas (trim + toUpperCase). Si ya existe un tipo
 * con el mismo `name` (case-insensitive efectivo), devuelve 409 CGT-001.
 *
 */
export const createCargoType = <ThrowOnError extends boolean = false>(options: Options<CreateCargoTypeData, ThrowOnError>) => (options.client ?? client).post<CreateCargoTypeResponses, CreateCargoTypeErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cargo-types',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Listar monedas (sin paginar — pocos registros)
 */
export const listCurrencies = <ThrowOnError extends boolean = false>(options?: Options<ListCurrenciesData, ThrowOnError>) => (options?.client ?? client).get<ListCurrenciesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/currencies',
    ...options
});

/**
 * Listar términos de pago
 */
export const listPaymentTerms = <ThrowOnError extends boolean = false>(options?: Options<ListPaymentTermsData, ThrowOnError>) => (options?.client ?? client).get<ListPaymentTermsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/payment-terms',
    ...options
});

/**
 * Listar tipos de servicio cotizables
 */
export const listQuotationServiceTypes = <ThrowOnError extends boolean = false>(options?: Options<ListQuotationServiceTypesData, ThrowOnError>) => (options?.client ?? client).get<ListQuotationServiceTypesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotation-service-types',
    ...options
});

/**
 * Buscar clientes (paginado por volumen)
 *
 * Listado paginado de clientes. Filtra por substring case-insensitive en
 * `name` y `ruc` cuando se envía `q` (ILIKE acelerado por GIN trgm).
 * Default sort: `name ASC`. Cuando hay `q`, ranking primario por
 * `similarity(name|ruc, q) DESC`, tiebreak `name ASC`.
 * Para no filtrar, OMITIR el parámetro `q` (no enviarlo vacío).
 * Un `isActive` no booleano se interpreta como `false` (binder de JAX-RS).
 *
 */
export const listClients = <ThrowOnError extends boolean = false>(options?: Options<ListClientsData, ThrowOnError>) => (options?.client ?? client).get<ListClientsResponses, ListClientsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clients',
    ...options
});

/**
 * Crear cliente al vuelo
 */
export const createClient = <ThrowOnError extends boolean = false>(options: Options<CreateClientData, ThrowOnError>) => (options.client ?? client).post<CreateClientResponses, CreateClientErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Listar cotizaciones con búsqueda y filtros
 *
 * Listado paginado de cotizaciones. Todos los filtros son opcionales y se
 * combinan con AND. Orden fijo: `createdAt` descendente (más recientes primero).
 *
 * `totalAmount` e `itemsCount` se calculan en runtime desde los ítems
 * (no se persisten). `itemsCount` cuenta solo ítems root (los hijos del
 * Servicio Integral no cuentan). Un listado sin resultados devuelve `200`
 * con `content: []` (no 404).
 *
 */
export const listQuotations = <ThrowOnError extends boolean = false>(options?: Options<ListQuotationsData, ThrowOnError>) => (options?.client ?? client).get<ListQuotationsResponses, ListQuotationsErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotations',
    ...options
});

/**
 * Crear cotización
 *
 * Crea una cotización con su cabecera + ítems + stand-by costs en una
 * transacción atómica. El backend genera el `code` (formato `YYYY-NNNNN`)
 * usando advisory lock por año (reinicio anual automático del contador).
 *
 */
export const createQuotation = <ThrowOnError extends boolean = false>(options: Options<CreateQuotationData, ThrowOnError>) => (options.client ?? client).post<CreateQuotationResponses, CreateQuotationErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Configuración pública del módulo de cotizaciones
 *
 * Devuelve constantes runtime del módulo (IGV vigente, máximo de ítems
 * root, validez por defecto). El frontend lo usa para precargar el
 * wizard y mostrar previews sin hardcodear los valores.
 *
 * Backend responde desde `app.quotations.*` properties + constantes del
 * validator. Cacheable agresivamente (cambia raramente).
 *
 */
export const getQuotationConfig = <ThrowOnError extends boolean = false>(options?: Options<GetQuotationConfigData, ThrowOnError>) => (options?.client ?? client).get<GetQuotationConfigResponses, GetQuotationConfigErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotations/config',
    ...options
});

/**
 * Obtener detalle de una cotización
 *
 * Devuelve la cotización completa: cabecera + items (jerárquicos
 * con `children` del Servicio Integral) + totales calculados +
 * `expiresAt` computado + `isExpired` flag runtime (`now() > expiresAt`).
 *
 * **`isExpired`** se recomputa en cada GET (no se cachea server-side).
 * El cliente NO debe persistir el valor — el flag puede cambiar entre
 * requests consecutivos si la cotización venció en el medio.
 *
 * **Totales** recalculados desde items: subtotal por item root, IGV
 * usando el snapshot `item.igvPercentage` persistido (no el config
 * actual) — preserva integridad del documento firmado.
 *
 * El header `ETag` viene con el `updatedAt` del recurso — el cliente
 * puede usarlo para futuros `PUT/PATCH` con `If-Match` (optimistic
 * locking). Mismo formato exacto que el ETag del POST.
 *
 */
export const getQuotation = <ThrowOnError extends boolean = false>(options: Options<GetQuotationData, ThrowOnError>) => (options.client ?? client).get<GetQuotationResponses, GetQuotationErrors, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotations/{id}',
    ...options
});

/**
 * Descargar o previsualizar el PDF de la cotización
 */
export const downloadQuotationPdf = <ThrowOnError extends boolean = false>(options: Options<DownloadQuotationPdfData, ThrowOnError>) => (options.client ?? client).get<DownloadQuotationPdfResponses, DownloadQuotationPdfErrors, ThrowOnError>({
    responseType: 'blob',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quotations/{id}/pdf',
    ...options
});
