// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api/v1' | (string & {});
};

export type Problem = {
    /**
     * URI que identifica el tipo de error (ver catálogo de errores)
     */
    type: string;
    title: string;
    status: number;
    detail?: string | null;
    instance?: string | null;
    /**
     * Código corto del error para que el frontend pueda matchear sin parsear `detail`.
     */
    code?: string | null;
    /**
     * Identificador de la traza para correlacionar con logs.
     */
    traceId?: string | null;
    /**
     * Errores de validación por campo (presente solo cuando aplica).
     */
    errors?: Array<{
        field: string;
        message: string;
        code?: string | null;
    }>;
};

export type UserRole = 'admin' | 'sales' | 'dispatcher' | 'general_manager' | 'operations_manager' | 'finance_manager' | 'warehouse_keeper';

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    /**
     * JWT de acceso
     */
    token: string;
    /**
     * Token para renovar la sesión sin re-login
     */
    refreshToken?: string | null;
    expiresAt: string;
    /**
     * Segundos hasta expiración del access token
     */
    expiresIn: number;
    user: UserResponse;
};

export type RefreshRequest = {
    /**
     * JWT firmado emitido previamente por /auth/login o /auth/refresh.
     */
    refreshToken: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

/**
 * Referencia mínima a un usuario (para embeber en respuestas)
 */
export type UserRef = {
    id: number;
    username: string;
    fullName: string;
    /**
     * Cargo del trabajador (ej: Ejecutiva de Ventas)
     */
    position?: string | null;
};

export type UserResponse = UserRef & {
    role: UserRole;
    isActive: boolean;
};

export type CurrencyResponse = {
    id: number;
    code: string;
    symbol: string;
    name?: string | null;
    isActive: boolean;
};

export type PaymentTermResponse = {
    id: number;
    name: string;
    days: number;
    isActive: boolean;
};

export type ConditionResponse = {
    id: number;
    text: string;
    displayOrder: number;
    isActive: boolean;
};

export type QuotationConditionResponse = {
    id: number;
    text: string;
    displayOrder: number;
    /**
     * true salvo que la condicion se haya desactivado en el catalogo tras linkearse (snapshot historico, RN-05).
     */
    isActive: boolean;
};

export type CargoTypeRef = {
    id: number;
    name: string;
};

export type CargoTypeResponse = CargoTypeRef & {
    description?: string | null;
    standardWeight: number;
    standardLength?: number | null;
    standardWidth?: number | null;
    standardHeight?: number | null;
    isActive: boolean;
};

export type PageOfCargoType = PageMeta & {
    content: Array<CargoTypeResponse>;
};

export type CargoTypeRequest = {
    name: string;
    description?: string | null;
    standardWeight: number;
    standardLength?: number | null;
    standardWidth?: number | null;
    standardHeight?: number | null;
};

/**
 * Referencia a un cliente con datos de contacto (live, no snapshot).
 * Si el cliente actualiza sus datos, las cotizaciones existentes verán los
 * nuevos valores en su `client` embebido, excepto `quotations.contactName`
 * (que sí se persiste como snapshot independiente).
 *
 */
export type ClientRef = {
    id: number;
    name: string;
    ruc: string;
    phone?: string | null;
    contactName?: string | null;
};

export type ClientResponse = ClientRef & {
    isActive: boolean;
    createdAt: string;
};

export type ClientRequest = {
    name: string;
    ruc: string;
    phone?: string | null;
    contactName?: string | null;
};

export type PageMeta = {
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
    /**
     * Cantidad de items en la página actual
     */
    numberOfElements: number;
    /**
     * ¿Es la primera página?
     */
    first: boolean;
    /**
     * ¿Es la última página?
     */
    last: boolean;
    /**
     * ¿La página actual está vacía?
     */
    empty: boolean;
};

export type PageOfClient = PageMeta & {
    content: Array<ClientResponse>;
};

/**
 * Versión reducida de cotización para el listado. `client` usa el subset
 * del bounded context (id+name+ruc, consistente con el detalle).
 * `totalAmount`/`itemsCount` se computan en runtime (no persistidos);
 * `itemsCount` cuenta solo ítems root.
 *
 */
export type QuotationSummary = {
    id: number;
    code: string;
    quotationType: QuotationType;
    status: QuotationStatus;
    client: QuotationClientSummary;
    currencyCode: string;
    totalAmount: number;
    /**
     * Cantidad de ítems root (no incluye hijos del Servicio Integral)
     */
    itemsCount: number;
    validityDays: number;
    expiresAt?: string;
    isExpired: boolean;
    origin?: string | null;
    destination?: string | null;
    createdAt: string;
    createdBy: UserResponse;
};

export type PageOfQuotationSummary = PageMeta & {
    content: Array<QuotationSummary>;
};

/**
 * Categoría del servicio. El backend la **computa** desde el prefijo del
 * `code` (S→SERVICIO, A→ALQUILER, C→COMPLEMENTARIO, I→INTEGRAL): no es
 * columna en BD. Se expone en el response para que el frontend filtre sin
 * conocer la convención del prefijo.
 *
 * Reglas del wizard:
 * - `quotationType=TRANSPORTE` → muestra SERVICIO + COMPLEMENTARIO + INTEGRAL
 * - `quotationType=ALQUILER`   → muestra solo ALQUILER
 *
 */
export type QuotationServiceKind = 'SERVICIO' | 'ALQUILER' | 'COMPLEMENTARIO' | 'INTEGRAL';

export type QuotationServiceTypeResponse = QuotationServiceTypeRef & {
    description?: string | null;
    isActive: boolean;
};

/**
 * - `TRANSPORTE`: requiere `origin` y `destination`. Usa tipos de servicio de transporte y complementarios.
 * - `ALQUILER`: sin ruta. Solo tipos de servicio de alquiler.
 *
 */
export type QuotationType = 'TRANSPORTE' | 'ALQUILER';

/**
 * Ciclo de vida (eje único). Máquina de estados (ADR-004):
 * `DRAFT → SENT → {ACCEPTED | REJECTED | EXPIRED}`.
 *
 * - `DRAFT`: cotización en edición, no enviada al cliente.
 * - `SENT`: ya enviada al cliente. Único estado que puede vencer.
 * - `ACCEPTED`: el cliente la aceptó. Terminal (inmutable).
 * - `REJECTED`: el cliente la rechazó (lleva `rejectionReason`). Terminal (inmutable).
 * - `EXPIRED`: venció sin respuesta. Terminal (inmutable). Lo produce el job, no el usuario.
 *
 * `isExpired` se deriva del `status`: es `true` si y solo si `status == EXPIRED`.
 * El job de vencimiento diario (ADR-005) pasa `SENT → EXPIRED` cuando
 * `createdAt + validityDays < now()`; mientras tanto una `SENT` vencida sigue
 * reportando `isExpired=false` (ventana ≤24h hasta la próxima corrida). `DRAFT` y
 * los terminales no-`EXPIRED` devuelven `false`.
 *
 */
export type QuotationStatus = 'DRAFT' | 'SENT' | 'ACCEPTED' | 'REJECTED' | 'EXPIRED';

export type QuotationServiceTypeRef = {
    id: number;
    code: string;
    name: string;
    kind: QuotationServiceKind;
};

export type QuotationStandbyCostRequest = {
    pricePerDay: number;
    includesIgv?: boolean;
};

export type QuotationStandbyCostResponse = {
    id: number;
    pricePerDay: number;
    includesIgv: boolean;
};

/**
 * Constantes runtime del módulo Quotations expuestas al frontend.
 * Los valores vienen del config del backend (`app.quotations.*`) o de
 * constantes del validator. Cacheable agresivamente (raramente cambian).
 *
 */
export type QuotationConfigResponse = {
    /**
     * IGV nacional vigente. Se persiste como snapshot en cada `quotation_items.igv_percentage` al crear.
     */
    igvPercentage: number;
    /**
     * Máximo de ítems root permitidos por cotización (hijos del Servicio Integral no cuentan).
     */
    maxRootItems: number;
    /**
     * Validez por defecto sugerida para precargar el form (el usuario puede editarla).
     */
    defaultValidityDays: number;
};

export type QuotationClientSummary = {
    id: number;
    /**
     * Razon social del cliente
     */
    name: string;
    ruc: string;
};

export type QuotationCurrencySummary = {
    id: number;
    /**
     * Codigo ISO 4217
     */
    code: string;
    symbol: string;
};

export type QuotationPaymentTermSummary = {
    id: number;
    name: string;
    days: number;
};

export type QuotationServiceTypeSummary = {
    id: number;
    code: string;
    name: string;
    /**
     * Categoria del servicio (SERVICIO/ALQUILER/COMPLEMENTARIO/INTEGRAL)
     */
    kind: string;
};

/**
 * Subset minimo del tipo de carga para embeber en items de la cotizacion.
 * Las dimensiones del catalogo (standardWeight/Length/Width/Height) NO se
 * incluyen aca: el item persiste su propio weightKg/lengthMeters/...
 * como snapshot. Los valores de referencia del catalogo siguen disponibles
 * via GET /catalogs/cargo-types/{id} si se necesitan.
 *
 */
export type QuotationCargoTypeSummary = {
    id: number;
    name: string;
};

/**
 * Item de cotización. **`unitPrice` es requerido para ítems root**; para hijos del
 * Servicio Integral debe omitirse o enviarse como 0 (en su lugar puede enviarse
 * `internalReferencePrice`).
 *
 */
export type QuotationItemRequest = {
    /**
     * Si se omite, lo asigna el backend en orden de aparición. Si la cotización tiene Integral, debe ser `1`.
     */
    itemNumber?: number | null;
    /**
     * Para ítems hijos del Integral, referencia al `itemNumber` del padre dentro del mismo request (siempre `1`).
     */
    parentItemNumber?: number | null;
    serviceTypeId: number;
    cargoTypeId?: number | null;
    observations?: string | null;
    weightKg?: number | null;
    lengthMeters?: number | null;
    widthMeters?: number | null;
    heightMeters?: number | null;
    quantity: number;
    /**
     * Requerido para ítems root. Para hijos del Integral debe omitirse o ser 0.
     */
    unitPrice?: number | null;
    /**
     * Solo válido para hijos del Integral. Opcional. NO se muestra en el PDF.
     */
    internalReferencePrice?: number | null;
    /**
     * Solo válido si `serviceTypeId` corresponde a SEG.
     */
    insuredAmount?: number | null;
    standby?: QuotationStandbyCostRequest;
};

/**
 * Ítem de cotización. Puede ser **root** (sin `parentItemId`) o **hijo del Servicio
 * Integral** (con `parentItemId` apuntando al padre).
 *
 * **Pricing según tipo:**
 * - Ítems root: `unitPrice` es el precio que paga el cliente, IGV calculado al 18%.
 * - Hijos del Integral: `unitPrice` no aplica (siempre 0); usan `internalReferencePrice`
 * opcional, que es referencia histórica interna y NO se muestra en el PDF al cliente.
 * La suma de referencias de hijos puede exceder el precio del padre (es el descuento
 * implícito del paquete Integral).
 *
 */
export type QuotationItemResponse = {
    id: number;
    /**
     * NULL para ítems root. Set para ítems hijos del Servicio Integral.
     */
    parentItemId?: number | null;
    itemNumber: number;
    /**
     * Numeración de presentación jerárquica: root "1","2"; hijo del Integral "1.a","1.b". Derivada de itemNumber + jerarquía, NO persistida. El frontend la muestra; itemNumber sigue siendo la numeración técnica (plana, contigua).
     */
    displayLabel: string;
    serviceType: QuotationServiceTypeSummary;
    cargoType?: QuotationCargoTypeSummary;
    observations?: string | null;
    weightKg?: number | null;
    lengthMeters?: number | null;
    widthMeters?: number | null;
    heightMeters?: number | null;
    quantity: number;
    /**
     * Precio unitario que paga el cliente. Aplica solo para ítems root. En hijos del Integral siempre es 0 (usar `internalReferencePrice`).
     */
    unitPrice?: number;
    /**
     * Precio interno de referencia. Solo aplica para ítems hijos del Servicio Integral. NO se muestra en el PDF al cliente. Opcional.
     */
    internalReferencePrice?: number | null;
    igvPercentage: number;
    /**
     * `unitPrice * quantity` para root; 0 para hijos del Integral (no entran al total de la cotización).
     */
    subtotal: number;
    /**
     * Solo aplica para ítems de tipo Seguro de Carga (SEG).
     */
    insuredAmount?: number | null;
    standby?: QuotationStandbyCostResponse;
    /**
     * Ítems hijos (presente solo en ítems padre del Servicio Integral).
     */
    children?: Array<QuotationItemResponse>;
};

/**
 * ## Reglas de negocio (validadas por backend)
 *
 * - **Máximo 5 ítems root** (los hijos del Servicio Integral no cuentan).
 * - **Servicio Integral**: si la cotización tiene un ítem con `serviceType.code='INT'`:
 * - debe ser el primer ítem (`itemNumber=1`),
 * - debe tener al menos **2 ítems hijos** (referenciados vía `parentItemNumber=1`),
 * - los hijos deben incluir al menos **1 servicio de tipo TRANSPORTE (kind=S)** y
 * al menos **1 servicio de tipo COMPLEMENTARIO (kind=C)**,
 * - solo puede haber un Integral por cotización.
 * - **Origen/destino**: requeridos si `quotationType=TRANSPORTE`, ignorados si `ALQUILER`.
 * - **`contactName`**: snapshot editable. Se precarga desde `client.contactName` en el
 * formulario, pero el usuario puede editarlo. Lo que se guarda es el valor final del
 * formulario, congelado al momento de crear/editar la cotización.
 * - **Anti-duplicado**: el backend rechaza con `409 QUO-002` si llega un POST con
 * mismo `clientId` + mismo set de `serviceTypeId`s + mismo usuario creador dentro
 * de los últimos 30 segundos (protección anti doble-click backend-side).
 *
 */
export type QuotationRequest = {
    quotationType: QuotationType;
    clientId: number;
    /**
     * Obligatorio — la cotización siempre se dirige a alguien. Snapshot al momento de cotizar (se precarga del cliente, el usuario puede editarlo, queda congelado).
     */
    contactName: string;
    /**
     * Snapshot editable del telefono de contacto (9 digitos numericos). Se precarga del cliente y queda congelado en la cotización.
     */
    contactPhone?: string | null;
    currencyId: number;
    paymentTermId?: number | null;
    tentativeServiceDate?: string | null;
    validityDays: number;
    /**
     * Requerido si `quotationType=TRANSPORTE`. Validado por backend.
     */
    origin?: string | null;
    /**
     * Requerido si `quotationType=TRANSPORTE`. Validado por backend.
     */
    destination?: string | null;
    /**
     * Observación opcional visible para el cliente (se renderiza en el PDF tras el stand-by y en la UI). Texto libre.
     */
    clientNote?: string | null;
    /**
     * Observación opcional SOLO interna. NUNCA se incluye en el PDF ni en ninguna salida hacia el cliente (RN-03).
     */
    internalNote?: string | null;
    /**
     * Lista plana de ítems root e hijos. Los hijos referencian al padre vía `parentItemNumber`. Máximo 5 ítems root (validado por backend).
     */
    items: Array<QuotationItemRequest>;
    /**
     * Ids de las condiciones generales del catálogo que aplican a la cotización
     * (checkboxes en el wizard). Opcional: `null` o `[]` = sin condiciones (el usuario
     * puede desmarcar todas). Máximo 20 elementos (`400 COM-001` si se excede). Al
     * crear/editar (escritura), todas deben existir y estar **activas** (Opción B): una
     * condición desactivada → `409 QUO-007`; ids repetidos o inexistentes → `400 COM-001`.
     *
     */
    conditionIds?: Array<number> | null;
};

export type QuotationResponse = {
    id: number;
    code: string;
    quotationType: QuotationType;
    status: QuotationStatus;
    client: QuotationClientSummary;
    /**
     * Snapshot del contacto al momento de cotizar (queda fijo aunque cambie el cliente master).
     */
    contactName?: string | null;
    /**
     * Snapshot del telefono de contacto al momento de cotizar (9 digitos). Queda fijo aunque cambie el cliente master.
     */
    contactPhone?: string | null;
    currency: QuotationCurrencySummary;
    paymentTerm?: QuotationPaymentTermSummary;
    tentativeServiceDate?: string | null;
    validityDays: number;
    /**
     * createdAt + validityDays (computado)
     */
    expiresAt: string;
    /**
     * status == EXPIRED (lo persiste el job diario, ADR-005; no se recalcula por fechas)
     */
    isExpired: boolean;
    origin?: string | null;
    destination?: string | null;
    /**
     * Observación visible para el cliente (PDF + UI).
     */
    clientNote?: string | null;
    /**
     * Observación SOLO interna; se devuelve a los roles que editan, nunca en el PDF (RN-03).
     */
    internalNote?: string | null;
    /**
     * Motivo del rechazo. Presente solo si status=REJECTED. INTERNO — se devuelve a los roles que editan, NUNCA en el PDF (ADR-007).
     */
    rejectionReason?: string | null;
    /**
     * Suma de items.subtotal
     */
    totalSubtotal: number;
    /**
     * IGV total
     */
    totalIgv: number;
    /**
     * Total = subtotal + IGV
     */
    totalAmount: number;
    items: Array<QuotationItemResponse>;
    /**
     * Condiciones generales linkeadas, ordenadas por displayOrder ASC (RN-04). Incluye TODAS las linkeadas, activas O inactivas (RN-05, snapshot). Vacia si no hay (nunca null).
     */
    conditions: Array<QuotationConditionResponse>;
    createdBy: UserResponse;
    updatedBy: UserResponse;
    createdAt: string;
    /**
     * Source de la versión para optimistic locking (mismo valor que el header ETag).
     */
    updatedAt: string;
};

export type WarehouseProductCategoryResponse = {
    id: number;
    name: string;
    description?: string | null;
    isActive: boolean;
};

export type WarehouseProductCategoryRequest = {
    name: string;
    description?: string | null;
};

export type WarehouseUnitOfMeasureResponse = {
    id: number;
    code: string;
    name: string;
    isActive: boolean;
};

export type WarehouseSupplierResponse = {
    id: number;
    name: string;
    ruc?: string | null;
    phone?: string | null;
    contactName?: string | null;
    isActive: boolean;
    createdAt: string;
};

export type WarehouseSupplierRequest = {
    name: string;
    ruc?: string | null;
    phone?: string | null;
    contactName?: string | null;
};

export type PageOfWarehouseSupplier = PageMeta & {
    content: Array<WarehouseSupplierResponse>;
};

export type PageOfWarehouseProduct = PageMeta & {
    content: Array<WarehouseProductResponse>;
};

export type WarehouseProductRequest = {
    /**
     * Único COMPUESTO con brand+partNumber (Δ-2, RN-WH10)
     */
    name: string;
    categoryId: number;
    unitOfMeasureId: number;
    brand?: string | null;
    partNumber?: string | null;
    /**
     * Características flexibles clave-valor (JSONB). Objeto libre; la UI lo edita como filas clave-valor.
     */
    attributes?: {
        [key: string]: string;
    };
    /**
     * Umbral de reposición: stock < minStock → badge "Bajo" (RN-WH11)
     */
    minStock?: number;
    observations?: string | null;
    /**
     * Soft delete del catálogo. En el POST se ignora (siempre nace activo).
     */
    isActive?: boolean;
};

/**
 * Como WarehouseProductRequest pero SIN unitOfMeasureId: la unidad de medida se fija al crear y es inmutable (P-1). Su edición se evaluará más adelante.
 */
export type WarehouseProductUpdateRequest = {
    /**
     * Único COMPUESTO con brand+partNumber (Δ-2, RN-WH10)
     */
    name: string;
    categoryId: number;
    brand?: string | null;
    partNumber?: string | null;
    /**
     * Características flexibles clave-valor (JSONB). Objeto libre; la UI lo edita como filas clave-valor.
     */
    attributes?: {
        [key: string]: string;
    };
    minStock?: number;
    observations?: string | null;
    /**
     * Soft delete del catálogo.
     */
    isActive?: boolean;
};

export type WarehouseProductResponse = {
    id: number;
    /**
     * SKU (autogenerado por el backend)
     */
    code: string;
    name: string;
    category: {
        id: number;
        name: string;
    };
    unitOfMeasure: {
        id: number;
        code: string;
        name: string;
    };
    brand?: string | null;
    partNumber?: string | null;
    /**
     * Objeto JSON libre clave-valor (JSONB). Nunca `null` (default `{}`).
     */
    attributes: {
        [key: string]: string;
    };
    minStock: number;
    observations?: string | null;
    isActive: boolean;
    /**
     * LEÍDO de la VIEW `almacen.product_stock` (RN-WH1 — nunca persistido, siempre exacto)
     */
    stock: number;
    /**
     * Derivado en código: `stock < minStock` (estricto). NO es columna.
     */
    lowStock: boolean;
    createdBy: UserResponse;
    createdAt: string;
    /**
     * Versión del recurso (source del optimistic locking). Para el `If-Match` del PUT usar el header `ETag` del GET/PUT, NO este campo del body (difieren por µs entre memoria y BD → 412 espurio).
     */
    updatedAt: string;
};

/**
 * Lectura puntual del stock disponible (form de retiro, validación en vivo).
 */
export type WarehouseProductStockResponse = {
    productId: number;
    /**
     * De la VIEW `almacen.product_stock`
     */
    stock: number;
    minStock: number;
    /**
     * Derivado: `stock < minStock`
     */
    lowStock: boolean;
};

/**
 * Tipo de movimiento de la VIEW `almacen.stock_movements`: `APERTURA`
 * (corte inicial, +), `ENTRADA` (ítem de factura activa, +), `SALIDA`
 * (retiro activo, −). Valores en español porque son los literales de la
 * VIEW del DDL congelado.
 *
 */
export type WarehouseKardexMovementType = 'APERTURA' | 'ENTRADA' | 'SALIDA';

export type WarehouseKardexMovementResponse = {
    movementType: WarehouseKardexMovementType;
    /**
     * SIEMPRE positiva (el signo lo da movementType)
     */
    quantity: number;
    /**
     * Saldo corrido DESPUÉS del movimiento (RN-WH13 — server-side sobre la historia completa)
     */
    balance: number;
    movedAt: string;
    /**
     * Id del origen: factura (ENTRADA) o retiro (SALIDA); null para APERTURA
     */
    sourceId?: number | null;
    /**
     * Etiqueta legible compuesta por el backend (es-PE)
     */
    reference: string;
    registeredBy: UserResponse;
};

export type PageOfWarehouseKardexMovement = PageMeta & {
    content: Array<WarehouseKardexMovementResponse>;
};

/**
 * Referencia mínima a un producto para embeber en ítems, retiros y aperturas.
 */
export type WarehouseProductSummary = {
    id: number;
    code?: string | null;
    name: string;
    /**
     * Código de la unidad de medida (para pintar cantidades)
     */
    unitCode: string;
};

export type WarehouseOpeningBalanceRequest = {
    productId: number;
    /**
     * Puede ser 0 (deja constancia del conteo)
     */
    quantity: number;
    observations?: string | null;
};

export type WarehouseOpeningBalanceResponse = {
    id: number;
    product: WarehouseProductSummary;
    quantity: number;
    observations?: string | null;
    registeredBy: UserResponse;
    registeredAt: string;
};

export type PageOfWarehouseOpeningBalance = PageMeta & {
    content: Array<WarehouseOpeningBalanceResponse>;
};

/**
 * Estado de entradas y retiros (columna + CHECK). `CANCELLED` = anulado con
 * motivo/quien/cuando; no mueve stock/kardex/reportes pero queda visible.
 *
 */
export type WarehouseRecordStatus = 'ACTIVE' | 'CANCELLED';

/**
 * Rastro del ultimo cambio, derivado del FIELD_EDIT mas reciente en almacen.audit_logs.
 */
export type WarehouseEditTrace = {
    by: UserResponse;
    at: string;
    /**
     * Justificacion dada al editar (>= 10 caracteres)
     */
    reason: string;
};

export type WarehouseInvoiceItemRequest = {
    productId: number;
    quantity: number;
    /**
     * En la moneda de la factura. Puede ser 0 (bonificacion).
     */
    unitPrice: number;
};

export type WarehousePurchaseInvoiceRequest = {
    supplierId: number;
    invoiceNumber: string;
    invoiceDate: string;
    /**
     * Guia de remision (1 factura -> 1 guia; dato de finanzas)
     */
    guideNumber?: string | null;
    /**
     * Fija la moneda de la factura (RN-WH7)
     */
    currencyId: number;
    observations?: string | null;
    items: Array<WarehouseInvoiceItemRequest>;
};

/**
 * Body del PUT. SIN `supplierId` (el proveedor es INMUTABLE: RN-WH4, proveedor
 * equivocado = anular y re-registrar). Los `items` REEMPLAZAN a los existentes.
 *
 */
export type WarehousePurchaseInvoiceUpdateRequest = {
    invoiceNumber: string;
    invoiceDate: string;
    guideNumber?: string | null;
    currencyId: number;
    observations?: string | null;
    items: Array<WarehouseInvoiceItemRequest>;
    /**
     * Justificacion de la edicion (RN-WH4). Va a almacen.audit_logs con el diff por campo.
     */
    reason: string;
};

export type WarehouseCancelRequest = {
    /**
     * Motivo de anulacion (RN-WH3). Va a cancel_reason y a almacen.audit_logs (CANCELLED).
     */
    reason: string;
};

export type WarehouseInvoiceItemResponse = {
    id: number;
    product: WarehouseProductSummary;
    quantity: number;
    unitPrice: number;
    /**
     * `quantity * unitPrice`, derivado en codigo, no persistido
     */
    subtotal: number;
};

export type WarehousePurchaseInvoiceResponse = {
    id: number;
    supplier: {
        id: number;
        name: string;
        ruc?: string | null;
    };
    invoiceNumber: string;
    invoiceDate: string;
    guideNumber?: string | null;
    currency: {
        id: number;
        code: string;
        symbol: string;
    };
    observations?: string | null;
    items: Array<WarehouseInvoiceItemResponse>;
    /**
     * Suma de items.subtotal en la moneda de la factura, derivado en codigo, nunca persistido
     */
    total: number;
    status: WarehouseRecordStatus;
    /**
     * Presente solo si status=CANCELLED
     */
    cancelReason?: string | null;
    cancelledBy?: UserResponse;
    cancelledAt?: string | null;
    lastEdit?: WarehouseEditTrace;
    registeredBy: UserResponse;
    createdAt: string;
    /**
     * Source de la version, usar el header ETag opaco en If-Match, NO este valor
     */
    updatedAt: string;
};

/**
 * Fila del listado de Entradas.
 */
export type WarehousePurchaseInvoiceSummary = {
    id: number;
    supplier: {
        id: number;
        name: string;
    };
    invoiceNumber: string;
    invoiceDate: string;
    guideNumber?: string | null;
    currencyCode: string;
    itemsCount: number;
    /**
     * Derivado de los items (no persistido)
     */
    total: number;
    status: WarehouseRecordStatus;
    cancelReason?: string | null;
    registeredBy: UserResponse;
    createdAt: string;
};

export type PageOfWarehousePurchaseInvoiceSummary = PageMeta & {
    content: Array<WarehousePurchaseInvoiceSummary>;
};

/**
 * Trabajador de public.workers (catalogo compartido con v1, read-only desde v2).
 */
export type WorkerResponse = {
    id: number;
    fullName: string;
    position?: string | null;
    isActive: boolean;
};

/**
 * Subtipo de la flota (disyunto y total). ESCORT = vehiculo escolta.
 */
export type FleetUnitKind = 'TRACTOR' | 'TRAILER' | 'ESCORT';

/**
 * Referencia minima a una unidad de flota; la direccion completa es el par (kind, id).
 */
export type FleetUnitRef = {
    kind: FleetUnitKind;
    id: number;
    plate: string;
};

/**
 * Unidad de flota unificada (GET /fleet-units). Extiende FleetUnitRef con los
 * datos del subtipo. `brand`/`model` pueden ser null (las carretas no los tienen).
 *
 */
export type FleetUnitResponse = FleetUnitRef & {
    brand?: string | null;
    model?: string | null;
    isActive: boolean;
};

/**
 * RN-WH2: `receivedByWorkerId` SIEMPRE obligatorio; unidad destino OPCIONAL y a lo
 * sumo UNA (tractorId | trailerId | escortVehicleId, subtipos disyuntos; mas de una
 * -> 400 WH-005). `withdrawnAt` lo asigna el server.
 *
 */
export type WarehouseWithdrawalRequest = {
    productId: number;
    /**
     * > 0 y <= stock disponible (en transaccion -> 409 WH-001)
     */
    quantity: number;
    /**
     * Quien recibe (FK public.workers). Obligatorio.
     */
    receivedByWorkerId: number;
    tractorId?: number | null;
    trailerId?: number | null;
    escortVehicleId?: number | null;
    observations?: string | null;
};

/**
 * Body del PUT. SIN `productId`: el producto es INMUTABLE (RN-WH4, producto equivocado
 * = anular y crear otro). La unidad de flota se REEMPLAZA (los tres campos null la
 * quitan; a lo sumo una).
 *
 */
export type WarehouseWithdrawalUpdateRequest = {
    /**
     * Subirla valida contra el disponible SIN contar este retiro (409 WH-001); bajarla siempre es segura
     */
    quantity: number;
    receivedByWorkerId: number;
    tractorId?: number | null;
    trailerId?: number | null;
    escortVehicleId?: number | null;
    observations?: string | null;
    /**
     * Justificacion de la edicion (RN-WH4). Va a `almacen.audit_logs`.
     */
    reason: string;
};

export type WarehouseWithdrawalResponse = {
    id: number;
    product: WarehouseProductSummary;
    quantity: number;
    /**
     * Lo asigna el server al registrar
     */
    withdrawnAt: string;
    receivedBy: WorkerResponse;
    fleetUnit?: FleetUnitRef;
    observations?: string | null;
    status: WarehouseRecordStatus;
    /**
     * Presente solo si status=CANCELLED
     */
    cancelReason?: string | null;
    cancelledBy?: UserResponse;
    cancelledAt?: string | null;
    lastEdit?: WarehouseEditTrace;
    registeredBy: UserResponse;
    /**
     * Source de la version, usar el header ETag opaco en If-Match
     */
    updatedAt: string;
};

export type PageOfWarehouseWithdrawal = PageMeta & {
    content: Array<WarehouseWithdrawalResponse>;
};

/**
 * KPIs del strip de Existencias. Mes calendario en curso (America/Lima); solo ACTIVOS.
 */
export type WarehouseStatsResponse = {
    activeProducts: number;
    /**
     * Productos activos con stock < minStock (RN-WH11)
     */
    lowStockCount: number;
    /**
     * Facturas ACTIVAS registradas este mes (createdAt)
     */
    entriesThisMonth: number;
    /**
     * Retiros ACTIVOS registrados este mes (withdrawnAt)
     */
    withdrawalsThisMonth: number;
};

/**
 * Corte del reporte (los 4 de la pantalla Reportes):
 * - `BY_UNIT`: consumo por unidad de flota (retiros sin unidad -> "Sin unidad asignada")
 * - `BY_PERIOD`: consumo por semana (lunes como clave, en `detail`)
 * - `BY_PRODUCT`: consumo por producto (`count` = unidades retiradas)
 * - `BY_SUPPLIER`: compras por proveedor (facturas activas por `invoiceDate`)
 *
 */
export type WarehouseReportCut = 'BY_UNIT' | 'BY_PERIOD' | 'BY_PRODUCT' | 'BY_SUPPLIER';

/**
 * Fila agregada. RN-WH7 bi-moneda SIN conversion: `amountPEN` y `amountUSD`
 * acumulan por separado segun la moneda registrada (catalogo activo = PEN + USD).
 *
 */
export type WarehouseReportRowResponse = {
    /**
     * Etiqueta del grupo (ej: "Tracto ABC123", "Semana del 22/06", producto, proveedor)
     */
    label: string;
    /**
     * Dato secundario (unidad de medida en BY_PRODUCT, fecha ISO del lunes en BY_PERIOD)
     */
    detail?: string | null;
    /**
     * Nro de movimientos (o unidades retiradas en BY_PRODUCT)
     */
    count: number;
    /**
     * Valorizacion de referencia en PEN (salidas: ultimo precio de compra del producto)
     */
    amountPEN: number;
    /**
     * Valorizacion de referencia en USD
     */
    amountUSD: number;
};

export type WarehouseReportResponse = {
    cut: WarehouseReportCut;
    dateFrom: string;
    dateTo: string;
    /**
     * Orden: BY_PERIOD cronologico ASC; el resto por monto total DESC. Lista vacia si no hubo movimientos (nunca null).
     */
    rows: Array<WarehouseReportRowResponse>;
    totalPEN: number;
    totalUSD: number;
    totalCount: number;
};

/**
 * Página (base 0)
 */
export type Page = number;

/**
 * Tamaño de página (máx. 100)
 */
export type Size = number;

export type IdLong = number;

/**
 * ETag/version del recurso para optimistic locking.
 */
export type IfMatch = string;

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Solicitud inválida (campos faltantes o mal formados)
     */
    400: Problem;
    /**
     * Credenciales inválidas o usuario inactivo
     */
    401: Problem;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login exitoso
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Refresh token inválido o expirado
     */
    401: Problem;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Token renovado
     */
    200: LoginResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validación de contraseña fallida o contraseña actual incorrecta
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Contraseña actualizada
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * El usuario del token ya no existe
     */
    404: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListCargoTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Búsqueda libre por nombre (substring case-insensitive; ranking por similarity). Mínimo 3 caracteres. Para no filtrar, omitir el parámetro.
         */
        q?: string;
        isActive?: boolean;
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
    };
    url: '/cargo-types';
};

export type ListCargoTypesErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListCargoTypesError = ListCargoTypesErrors[keyof ListCargoTypesErrors];

export type ListCargoTypesResponses = {
    /**
     * OK
     */
    200: PageOfCargoType;
};

export type ListCargoTypesResponse = ListCargoTypesResponses[keyof ListCargoTypesResponses];

export type CreateCargoTypeData = {
    body: CargoTypeRequest;
    path?: never;
    query?: never;
    url: '/cargo-types';
};

export type CreateCargoTypeErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateCargoTypeError = CreateCargoTypeErrors[keyof CreateCargoTypeErrors];

export type CreateCargoTypeResponses = {
    /**
     * Creado
     */
    201: CargoTypeResponse;
};

export type CreateCargoTypeResponse = CreateCargoTypeResponses[keyof CreateCargoTypeResponses];

export type ListCurrenciesData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/currencies';
};

export type ListCurrenciesErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListCurrenciesError = ListCurrenciesErrors[keyof ListCurrenciesErrors];

export type ListCurrenciesResponses = {
    /**
     * OK
     */
    200: Array<CurrencyResponse>;
};

export type ListCurrenciesResponse = ListCurrenciesResponses[keyof ListCurrenciesResponses];

export type ListPaymentTermsData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/payment-terms';
};

export type ListPaymentTermsErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListPaymentTermsError = ListPaymentTermsErrors[keyof ListPaymentTermsErrors];

export type ListPaymentTermsResponses = {
    /**
     * OK
     */
    200: Array<PaymentTermResponse>;
};

export type ListPaymentTermsResponse = ListPaymentTermsResponses[keyof ListPaymentTermsResponses];

export type ListQuotationConditionsData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/quotation-conditions';
};

export type ListQuotationConditionsErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListQuotationConditionsError = ListQuotationConditionsErrors[keyof ListQuotationConditionsErrors];

export type ListQuotationConditionsResponses = {
    /**
     * OK
     */
    200: Array<ConditionResponse>;
};

export type ListQuotationConditionsResponse = ListQuotationConditionsResponses[keyof ListQuotationConditionsResponses];

export type ListQuotationServiceTypesData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/quotation-service-types';
};

export type ListQuotationServiceTypesErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListQuotationServiceTypesError = ListQuotationServiceTypesErrors[keyof ListQuotationServiceTypesErrors];

export type ListQuotationServiceTypesResponses = {
    /**
     * OK
     */
    200: Array<QuotationServiceTypeResponse>;
};

export type ListQuotationServiceTypesResponse = ListQuotationServiceTypesResponses[keyof ListQuotationServiceTypesResponses];

export type ListClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Búsqueda libre por nombre o RUC (substring case-insensitive; ranking por similarity). Mínimo 3 caracteres. Para no filtrar, omitir el parámetro.
         */
        q?: string;
        isActive?: boolean;
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
    };
    url: '/clients';
};

export type ListClientsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListClientsError = ListClientsErrors[keyof ListClientsErrors];

export type ListClientsResponses = {
    /**
     * OK
     */
    200: PageOfClient;
};

export type ListClientsResponse = ListClientsResponses[keyof ListClientsResponses];

export type CreateClientData = {
    body: ClientRequest;
    path?: never;
    query?: never;
    url: '/clients';
};

export type CreateClientErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors];

export type CreateClientResponses = {
    /**
     * Creado
     */
    201: ClientResponse;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type ListQuotationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
        /**
         * Búsqueda libre con coincidencia parcial sobre: `code`, `client.name`,
         * `client.ruc`, `origin`, `destination`. Usa pg_trgm para fuzzy matching.
         * Mínimo 3 caracteres.
         *
         */
        q?: string;
        status?: QuotationStatus;
        quotationType?: QuotationType;
        clientId?: number;
        createdById?: number;
        currencyId?: number;
        /**
         * Filtra cotizaciones que tengan al menos un ítem (root o hijo) con este cargo type
         */
        cargoTypeId?: number;
        /**
         * Filtra cotizaciones que tengan al menos un ítem (root o hijo) con este service type
         */
        serviceTypeId?: number;
        /**
         * Filtro por `createdAt` desde (ISO date, inclusivo). Interpretado en zona horaria de Lima (UTC-5).
         */
        dateFrom?: string;
        /**
         * Filtro por `createdAt` hasta (ISO date, inclusivo del día completo). Interpretado en zona horaria de Lima (UTC-5).
         */
        dateTo?: string;
    };
    url: '/quotations';
};

export type ListQuotationsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListQuotationsError = ListQuotationsErrors[keyof ListQuotationsErrors];

export type ListQuotationsResponses = {
    /**
     * Listado paginado
     */
    200: PageOfQuotationSummary;
};

export type ListQuotationsResponse = ListQuotationsResponses[keyof ListQuotationsResponses];

export type CreateQuotationData = {
    body: QuotationRequest;
    path?: never;
    query?: never;
    url: '/quotations';
};

export type CreateQuotationErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateQuotationError = CreateQuotationErrors[keyof CreateQuotationErrors];

export type CreateQuotationResponses = {
    /**
     * Cotización creada
     */
    201: QuotationResponse;
};

export type CreateQuotationResponse = CreateQuotationResponses[keyof CreateQuotationResponses];

export type GetQuotationConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quotations/config';
};

export type GetQuotationConfigErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type GetQuotationConfigError = GetQuotationConfigErrors[keyof GetQuotationConfigErrors];

export type GetQuotationConfigResponses = {
    /**
     * Config vigente
     */
    200: QuotationConfigResponse;
};

export type GetQuotationConfigResponse = GetQuotationConfigResponses[keyof GetQuotationConfigResponses];

export type GetQuotationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/quotations/{id}';
};

export type GetQuotationErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetQuotationError = GetQuotationErrors[keyof GetQuotationErrors];

export type GetQuotationResponses = {
    /**
     * OK
     */
    200: QuotationResponse;
};

export type GetQuotationResponse = GetQuotationResponses[keyof GetQuotationResponses];

export type UpdateQuotationData = {
    body: QuotationRequest;
    headers?: {
        /**
         * ETag/version del recurso para optimistic locking.
         */
        'If-Match'?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/quotations/{id}';
};

export type UpdateQuotationErrors = {
    /**
     * Validación de reglas de negocio o intento de modificar un campo inmutable
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type UpdateQuotationError = UpdateQuotationErrors[keyof UpdateQuotationErrors];

export type UpdateQuotationResponses = {
    /**
     * Actualizada
     */
    200: QuotationResponse;
};

export type UpdateQuotationResponse = UpdateQuotationResponses[keyof UpdateQuotationResponses];

export type UpdateQuotationStatusData = {
    body: {
        /**
         * Destino de la transición. Solo destinos de usuario (DRAFT/EXPIRED no se exponen).
         */
        status: 'SENT' | 'ACCEPTED' | 'REJECTED';
        /**
         * Motivo del rechazo (texto libre, máx 500). Obligatorio Y exclusivo de
         * `status=REJECTED`. INTERNO — nunca se incluye en el PDF (ADR-007).
         *
         */
        rejectionReason?: string | null;
    };
    headers?: {
        /**
         * ETag/version del recurso para optimistic locking.
         */
        'If-Match'?: string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/quotations/{id}/status';
};

export type UpdateQuotationStatusErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type UpdateQuotationStatusError = UpdateQuotationStatusErrors[keyof UpdateQuotationStatusErrors];

export type UpdateQuotationStatusResponses = {
    /**
     * Estado actualizado
     */
    200: QuotationResponse;
};

export type UpdateQuotationStatusResponse = UpdateQuotationStatusResponses[keyof UpdateQuotationStatusResponses];

export type DownloadQuotationPdfData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        /**
         * Si `true`, sirve inline (Content-Disposition inline). Si `false` o se omite, fuerza descarga.
         */
        preview?: boolean;
    };
    url: '/quotations/{id}/pdf';
};

export type DownloadQuotationPdfErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type DownloadQuotationPdfError = DownloadQuotationPdfErrors[keyof DownloadQuotationPdfErrors];

export type DownloadQuotationPdfResponses = {
    /**
     * PDF generado
     */
    200: Blob | File;
};

export type DownloadQuotationPdfResponse = DownloadQuotationPdfResponses[keyof DownloadQuotationPdfResponses];

export type ListWarehouseProductCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/warehouse/product-categories';
};

export type ListWarehouseProductCategoriesErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseProductCategoriesError = ListWarehouseProductCategoriesErrors[keyof ListWarehouseProductCategoriesErrors];

export type ListWarehouseProductCategoriesResponses = {
    /**
     * Categorías
     */
    200: Array<WarehouseProductCategoryResponse>;
};

export type ListWarehouseProductCategoriesResponse = ListWarehouseProductCategoriesResponses[keyof ListWarehouseProductCategoriesResponses];

export type CreateWarehouseProductCategoryData = {
    body: WarehouseProductCategoryRequest;
    path?: never;
    query?: never;
    url: '/warehouse/product-categories';
};

export type CreateWarehouseProductCategoryErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Nombre duplicado → WH-010
     */
    409: Problem;
};

export type CreateWarehouseProductCategoryError = CreateWarehouseProductCategoryErrors[keyof CreateWarehouseProductCategoryErrors];

export type CreateWarehouseProductCategoryResponses = {
    /**
     * Creada
     */
    201: WarehouseProductCategoryResponse;
};

export type CreateWarehouseProductCategoryResponse = CreateWarehouseProductCategoryResponses[keyof CreateWarehouseProductCategoryResponses];

export type ListWarehouseUnitsOfMeasureData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/warehouse/units-of-measure';
};

export type ListWarehouseUnitsOfMeasureErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseUnitsOfMeasureError = ListWarehouseUnitsOfMeasureErrors[keyof ListWarehouseUnitsOfMeasureErrors];

export type ListWarehouseUnitsOfMeasureResponses = {
    /**
     * Unidades de medida
     */
    200: Array<WarehouseUnitOfMeasureResponse>;
};

export type ListWarehouseUnitsOfMeasureResponse = ListWarehouseUnitsOfMeasureResponses[keyof ListWarehouseUnitsOfMeasureResponses];

export type ListWarehouseSuppliersData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        isActive?: boolean;
        page?: number;
        size?: number;
    };
    url: '/warehouse/suppliers';
};

export type ListWarehouseSuppliersErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseSuppliersError = ListWarehouseSuppliersErrors[keyof ListWarehouseSuppliersErrors];

export type ListWarehouseSuppliersResponses = {
    /**
     * Página de proveedores
     */
    200: PageOfWarehouseSupplier;
};

export type ListWarehouseSuppliersResponse = ListWarehouseSuppliersResponses[keyof ListWarehouseSuppliersResponses];

export type CreateWarehouseSupplierData = {
    body: WarehouseSupplierRequest;
    path?: never;
    query?: never;
    url: '/warehouse/suppliers';
};

export type CreateWarehouseSupplierErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Duplicado de catálogo del módulo Almacén — nombre/código/RUC ya existe → WH-010
     */
    409: Problem;
};

export type CreateWarehouseSupplierError = CreateWarehouseSupplierErrors[keyof CreateWarehouseSupplierErrors];

export type CreateWarehouseSupplierResponses = {
    /**
     * Creado
     */
    201: WarehouseSupplierResponse;
};

export type CreateWarehouseSupplierResponse = CreateWarehouseSupplierResponses[keyof CreateWarehouseSupplierResponses];

export type ListWarehouseProductsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        categoryId?: number;
        isActive?: boolean;
        /**
         * Si `true`, solo productos con `stock < minStock` (badge "Bajo").
         */
        lowOnly?: boolean;
        page?: number;
        size?: number;
    };
    url: '/warehouse/products';
};

export type ListWarehouseProductsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseProductsError = ListWarehouseProductsErrors[keyof ListWarehouseProductsErrors];

export type ListWarehouseProductsResponses = {
    /**
     * Página de productos con stock
     */
    200: PageOfWarehouseProduct;
};

export type ListWarehouseProductsResponse = ListWarehouseProductsResponses[keyof ListWarehouseProductsResponses];

export type CreateWarehouseProductData = {
    body: WarehouseProductRequest;
    path?: never;
    query?: never;
    url: '/warehouse/products';
};

export type CreateWarehouseProductErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Duplicado de catálogo del módulo Almacén — nombre/código/RUC ya existe → WH-010
     */
    409: Problem;
};

export type CreateWarehouseProductError = CreateWarehouseProductErrors[keyof CreateWarehouseProductErrors];

export type CreateWarehouseProductResponses = {
    /**
     * Creado
     */
    201: WarehouseProductResponse;
};

export type CreateWarehouseProductResponse = CreateWarehouseProductResponses[keyof CreateWarehouseProductResponses];

export type GetWarehouseProductData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/products/{id}';
};

export type GetWarehouseProductErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetWarehouseProductError = GetWarehouseProductErrors[keyof GetWarehouseProductErrors];

export type GetWarehouseProductResponses = {
    /**
     * Producto con stock
     */
    200: WarehouseProductResponse;
};

export type GetWarehouseProductResponse = GetWarehouseProductResponses[keyof GetWarehouseProductResponses];

export type UpdateWarehouseProductData = {
    body: WarehouseProductUpdateRequest;
    headers: {
        'If-Match': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/products/{id}';
};

export type UpdateWarehouseProductErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * Duplicado de catálogo del módulo Almacén — nombre/código/RUC ya existe → WH-010
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type UpdateWarehouseProductError = UpdateWarehouseProductErrors[keyof UpdateWarehouseProductErrors];

export type UpdateWarehouseProductResponses = {
    /**
     * Actualizado
     */
    200: WarehouseProductResponse;
};

export type UpdateWarehouseProductResponse = UpdateWarehouseProductResponses[keyof UpdateWarehouseProductResponses];

export type GetWarehouseProductStockData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/products/{id}/stock';
};

export type GetWarehouseProductStockErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetWarehouseProductStockError = GetWarehouseProductStockErrors[keyof GetWarehouseProductStockErrors];

export type GetWarehouseProductStockResponses = {
    /**
     * Stock del producto
     */
    200: WarehouseProductStockResponse;
};

export type GetWarehouseProductStockResponse = GetWarehouseProductStockResponses[keyof GetWarehouseProductStockResponses];

export type GetWarehouseProductKardexData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        /**
         * Desde (inclusive, América/Lima)
         */
        dateFrom?: string;
        /**
         * Hasta (inclusive del día completo, América/Lima)
         */
        dateTo?: string;
        page?: number;
        size?: number;
    };
    url: '/warehouse/products/{id}/kardex';
};

export type GetWarehouseProductKardexErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetWarehouseProductKardexError = GetWarehouseProductKardexErrors[keyof GetWarehouseProductKardexErrors];

export type GetWarehouseProductKardexResponses = {
    /**
     * Página de movimientos
     */
    200: PageOfWarehouseKardexMovement;
};

export type GetWarehouseProductKardexResponse = GetWarehouseProductKardexResponses[keyof GetWarehouseProductKardexResponses];

export type ListWarehouseOpeningBalancesData = {
    body?: never;
    path?: never;
    query?: {
        productId?: number;
        page?: number;
        size?: number;
    };
    url: '/warehouse/opening-balances';
};

export type ListWarehouseOpeningBalancesErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseOpeningBalancesError = ListWarehouseOpeningBalancesErrors[keyof ListWarehouseOpeningBalancesErrors];

export type ListWarehouseOpeningBalancesResponses = {
    /**
     * Página de aperturas
     */
    200: PageOfWarehouseOpeningBalance;
};

export type ListWarehouseOpeningBalancesResponse = ListWarehouseOpeningBalancesResponses[keyof ListWarehouseOpeningBalancesResponses];

export type CreateWarehouseOpeningBalanceData = {
    body: WarehouseOpeningBalanceRequest;
    path?: never;
    query?: never;
    url: '/warehouse/opening-balances';
};

export type CreateWarehouseOpeningBalanceErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * WH-009 (apertura duplicada) o WH-011 (producto con movimientos)
     */
    409: Problem;
};

export type CreateWarehouseOpeningBalanceError = CreateWarehouseOpeningBalanceErrors[keyof CreateWarehouseOpeningBalanceErrors];

export type CreateWarehouseOpeningBalanceResponses = {
    /**
     * Registrado
     */
    201: WarehouseOpeningBalanceResponse;
};

export type CreateWarehouseOpeningBalanceResponse = CreateWarehouseOpeningBalanceResponses[keyof CreateWarehouseOpeningBalanceResponses];

export type ListWarehousePurchaseInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        supplierId?: number;
        status?: WarehouseRecordStatus;
        /**
         * `invoiceDate` desde (inclusive)
         */
        dateFrom?: string;
        /**
         * `invoiceDate` hasta (inclusive)
         */
        dateTo?: string;
        page?: number;
        size?: number;
    };
    url: '/warehouse/purchase-invoices';
};

export type ListWarehousePurchaseInvoicesErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehousePurchaseInvoicesError = ListWarehousePurchaseInvoicesErrors[keyof ListWarehousePurchaseInvoicesErrors];

export type ListWarehousePurchaseInvoicesResponses = {
    /**
     * Pagina de facturas
     */
    200: PageOfWarehousePurchaseInvoiceSummary;
};

export type ListWarehousePurchaseInvoicesResponse = ListWarehousePurchaseInvoicesResponses[keyof ListWarehousePurchaseInvoicesResponses];

export type CreateWarehousePurchaseInvoiceData = {
    body: WarehousePurchaseInvoiceRequest;
    path?: never;
    query?: never;
    url: '/warehouse/purchase-invoices';
};

export type CreateWarehousePurchaseInvoiceErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Nº de factura duplicado para ese proveedor (entre ACTIVAS) -> WH-002
     */
    409: Problem;
};

export type CreateWarehousePurchaseInvoiceError = CreateWarehousePurchaseInvoiceErrors[keyof CreateWarehousePurchaseInvoiceErrors];

export type CreateWarehousePurchaseInvoiceResponses = {
    /**
     * Creada
     */
    201: WarehousePurchaseInvoiceResponse;
};

export type CreateWarehousePurchaseInvoiceResponse = CreateWarehousePurchaseInvoiceResponses[keyof CreateWarehousePurchaseInvoiceResponses];

export type GetWarehousePurchaseInvoiceData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/purchase-invoices/{id}';
};

export type GetWarehousePurchaseInvoiceErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetWarehousePurchaseInvoiceError = GetWarehousePurchaseInvoiceErrors[keyof GetWarehousePurchaseInvoiceErrors];

export type GetWarehousePurchaseInvoiceResponses = {
    /**
     * Detalle completo
     */
    200: WarehousePurchaseInvoiceResponse;
};

export type GetWarehousePurchaseInvoiceResponse = GetWarehousePurchaseInvoiceResponses[keyof GetWarehousePurchaseInvoiceResponses];

export type UpdateWarehousePurchaseInvoiceData = {
    body: WarehousePurchaseInvoiceUpdateRequest;
    headers: {
        'If-Match': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/purchase-invoices/{id}';
};

export type UpdateWarehousePurchaseInvoiceErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * WH-006 (dejaria stock negativo) / WH-008 (anulada) / WH-002 (duplicado)
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type UpdateWarehousePurchaseInvoiceError = UpdateWarehousePurchaseInvoiceErrors[keyof UpdateWarehousePurchaseInvoiceErrors];

export type UpdateWarehousePurchaseInvoiceResponses = {
    /**
     * Actualizada
     */
    200: WarehousePurchaseInvoiceResponse;
};

export type UpdateWarehousePurchaseInvoiceResponse = UpdateWarehousePurchaseInvoiceResponses[keyof UpdateWarehousePurchaseInvoiceResponses];

export type CancelWarehousePurchaseInvoiceData = {
    body: WarehouseCancelRequest;
    headers: {
        'If-Match': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/purchase-invoices/{id}/cancel';
};

export type CancelWarehousePurchaseInvoiceErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * WH-007 (el stock quedaria negativo al descontarla) / WH-008 (ya anulada)
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type CancelWarehousePurchaseInvoiceError = CancelWarehousePurchaseInvoiceErrors[keyof CancelWarehousePurchaseInvoiceErrors];

export type CancelWarehousePurchaseInvoiceResponses = {
    /**
     * Anulada
     */
    200: WarehousePurchaseInvoiceResponse;
};

export type CancelWarehousePurchaseInvoiceResponse = CancelWarehousePurchaseInvoiceResponses[keyof CancelWarehousePurchaseInvoiceResponses];

export type ListWarehouseWithdrawalsData = {
    body?: never;
    path?: never;
    query?: {
        productId?: number;
        receivedByWorkerId?: number;
        tractorId?: number;
        trailerId?: number;
        escortVehicleId?: number;
        status?: WarehouseRecordStatus;
        /**
         * `withdrawnAt` desde (inclusive, America/Lima)
         */
        dateFrom?: string;
        /**
         * `withdrawnAt` hasta (inclusive del dia completo, America/Lima)
         */
        dateTo?: string;
        page?: number;
        size?: number;
    };
    url: '/warehouse/withdrawals';
};

export type ListWarehouseWithdrawalsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWarehouseWithdrawalsError = ListWarehouseWithdrawalsErrors[keyof ListWarehouseWithdrawalsErrors];

export type ListWarehouseWithdrawalsResponses = {
    /**
     * Pagina de retiros
     */
    200: PageOfWarehouseWithdrawal;
};

export type ListWarehouseWithdrawalsResponse = ListWarehouseWithdrawalsResponses[keyof ListWarehouseWithdrawalsResponses];

export type CreateWarehouseWithdrawalData = {
    body: WarehouseWithdrawalRequest;
    path?: never;
    query?: never;
    url: '/warehouse/withdrawals';
};

export type CreateWarehouseWithdrawalErrors = {
    /**
     * Validacion, incluye WH-005 (mas de una unidad) y WH-004 (catalogo)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Stock insuficiente -> WH-001
     */
    409: Problem;
};

export type CreateWarehouseWithdrawalError = CreateWarehouseWithdrawalErrors[keyof CreateWarehouseWithdrawalErrors];

export type CreateWarehouseWithdrawalResponses = {
    /**
     * Registrado
     */
    201: WarehouseWithdrawalResponse;
};

export type CreateWarehouseWithdrawalResponse = CreateWarehouseWithdrawalResponses[keyof CreateWarehouseWithdrawalResponses];

export type GetWarehouseWithdrawalData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/withdrawals/{id}';
};

export type GetWarehouseWithdrawalErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetWarehouseWithdrawalError = GetWarehouseWithdrawalErrors[keyof GetWarehouseWithdrawalErrors];

export type GetWarehouseWithdrawalResponses = {
    /**
     * Detalle
     */
    200: WarehouseWithdrawalResponse;
};

export type GetWarehouseWithdrawalResponse = GetWarehouseWithdrawalResponses[keyof GetWarehouseWithdrawalResponses];

export type UpdateWarehouseWithdrawalData = {
    body: WarehouseWithdrawalUpdateRequest;
    headers: {
        'If-Match': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/withdrawals/{id}';
};

export type UpdateWarehouseWithdrawalErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * WH-001 (excede stock sin contar este retiro) / WH-008 (anulado)
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type UpdateWarehouseWithdrawalError = UpdateWarehouseWithdrawalErrors[keyof UpdateWarehouseWithdrawalErrors];

export type UpdateWarehouseWithdrawalResponses = {
    /**
     * Actualizado
     */
    200: WarehouseWithdrawalResponse;
};

export type UpdateWarehouseWithdrawalResponse = UpdateWarehouseWithdrawalResponses[keyof UpdateWarehouseWithdrawalResponses];

export type CancelWarehouseWithdrawalData = {
    body: WarehouseCancelRequest;
    headers: {
        'If-Match': string;
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/warehouse/withdrawals/{id}/cancel';
};

export type CancelWarehouseWithdrawalErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
    /**
     * Ya anulado -> WH-008
     */
    409: Problem;
    /**
     * Optimistic lock — el recurso fue modificado desde que se leyó
     */
    412: Problem;
};

export type CancelWarehouseWithdrawalError = CancelWarehouseWithdrawalErrors[keyof CancelWarehouseWithdrawalErrors];

export type CancelWarehouseWithdrawalResponses = {
    /**
     * Anulado
     */
    200: WarehouseWithdrawalResponse;
};

export type CancelWarehouseWithdrawalResponse = CancelWarehouseWithdrawalResponses[keyof CancelWarehouseWithdrawalResponses];

export type GetWarehouseStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/warehouse/stats';
};

export type GetWarehouseStatsErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type GetWarehouseStatsError = GetWarehouseStatsErrors[keyof GetWarehouseStatsErrors];

export type GetWarehouseStatsResponses = {
    /**
     * Contadores del strip
     */
    200: WarehouseStatsResponse;
};

export type GetWarehouseStatsResponse = GetWarehouseStatsResponses[keyof GetWarehouseStatsResponses];

export type GetWarehouseReportData = {
    body?: never;
    path?: never;
    query: {
        cut: WarehouseReportCut;
        dateFrom: string;
        dateTo: string;
    };
    url: '/warehouse/reports';
};

export type GetWarehouseReportErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type GetWarehouseReportError = GetWarehouseReportErrors[keyof GetWarehouseReportErrors];

export type GetWarehouseReportResponses = {
    /**
     * Filas + totales por moneda
     */
    200: WarehouseReportResponse;
};

export type GetWarehouseReportResponse = GetWarehouseReportResponses[keyof GetWarehouseReportResponses];

export type ListWorkersData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        isActive?: boolean;
    };
    url: '/workers';
};

export type ListWorkersErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListWorkersError = ListWorkersErrors[keyof ListWorkersErrors];

export type ListWorkersResponses = {
    /**
     * Trabajadores
     */
    200: Array<WorkerResponse>;
};

export type ListWorkersResponse = ListWorkersResponses[keyof ListWorkersResponses];

export type ListFleetUnitsData = {
    body?: never;
    path?: never;
    query?: {
        kind?: FleetUnitKind;
        isActive?: boolean;
    };
    url: '/fleet-units';
};

export type ListFleetUnitsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListFleetUnitsError = ListFleetUnitsErrors[keyof ListFleetUnitsErrors];

export type ListFleetUnitsResponses = {
    /**
     * Unidades de flota
     */
    200: Array<FleetUnitResponse>;
};

export type ListFleetUnitsResponse = ListFleetUnitsResponses[keyof ListFleetUnitsResponses];
