// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api/v1' | (string & {});
};

export type Problem = {
    /**
     * URI que identifica el tipo de error (ver catálogo de errores)
     */
    type: string;
    title: string;
    status: number;
    detail?: string | null;
    instance?: string | null;
    /**
     * Código corto del error para que el frontend pueda matchear sin parsear `detail`.
     */
    code?: string | null;
    /**
     * Identificador de la traza para correlacionar con logs.
     */
    traceId?: string | null;
    /**
     * Errores de validación por campo (presente solo cuando aplica).
     */
    errors?: Array<{
        field: string;
        message: string;
        code?: string | null;
    }>;
};

export type UserRole = 'admin' | 'sales' | 'dispatcher' | 'general_manager' | 'operations_manager';

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    /**
     * JWT de acceso
     */
    token: string;
    /**
     * Token para renovar la sesión sin re-login
     */
    refreshToken?: string | null;
    expiresAt: string;
    /**
     * Segundos hasta expiración del access token
     */
    expiresIn: number;
    user: UserResponse;
};

export type RefreshRequest = {
    /**
     * JWT firmado emitido previamente por /auth/login o /auth/refresh.
     */
    refreshToken: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

/**
 * Referencia mínima a un usuario (para embeber en respuestas)
 */
export type UserRef = {
    id: number;
    username: string;
    fullName: string;
    /**
     * Cargo del trabajador (ej: Ejecutiva de Ventas)
     */
    position?: string | null;
};

export type UserResponse = UserRef & {
    role: UserRole;
    isActive: boolean;
};

export type CurrencyResponse = {
    id: number;
    code: string;
    symbol: string;
    name?: string | null;
    isActive: boolean;
};

export type PaymentTermResponse = {
    id: number;
    name: string;
    days: number;
    isActive: boolean;
};

export type CargoTypeRef = {
    id: number;
    name: string;
};

export type CargoTypeResponse = CargoTypeRef & {
    description?: string | null;
    standardWeight: number;
    standardLength?: number | null;
    standardWidth?: number | null;
    standardHeight?: number | null;
    isActive: boolean;
};

export type PageOfCargoType = PageMeta & {
    content: Array<CargoTypeResponse>;
};

export type CargoTypeRequest = {
    name: string;
    description?: string | null;
    standardWeight: number;
    standardLength?: number | null;
    standardWidth?: number | null;
    standardHeight?: number | null;
};

/**
 * Referencia a un cliente con datos de contacto (live, no snapshot).
 * Si el cliente actualiza sus datos, las cotizaciones existentes verán los
 * nuevos valores en su `client` embebido, excepto `quotations.contactName`
 * (que sí se persiste como snapshot independiente).
 *
 */
export type ClientRef = {
    id: number;
    name: string;
    ruc: string;
    phone?: string | null;
    contactName?: string | null;
};

export type ClientResponse = ClientRef & {
    isActive: boolean;
    createdAt: string;
};

export type ClientRequest = {
    name: string;
    ruc: string;
    phone?: string | null;
    contactName?: string | null;
};

export type PageMeta = {
    page: number;
    size: number;
    totalElements: number;
    totalPages: number;
    /**
     * Cantidad de items en la página actual
     */
    numberOfElements: number;
    /**
     * ¿Es la primera página?
     */
    first: boolean;
    /**
     * ¿Es la última página?
     */
    last: boolean;
    /**
     * ¿La página actual está vacía?
     */
    empty: boolean;
};

export type PageOfClient = PageMeta & {
    content: Array<ClientResponse>;
};

/**
 * Versión reducida de cotización para el listado. `client` usa el subset
 * del bounded context (id+name+ruc, consistente con el detalle).
 * `totalAmount`/`itemsCount` se computan en runtime (no persistidos);
 * `itemsCount` cuenta solo ítems root.
 *
 */
export type QuotationSummary = {
    id: number;
    code: string;
    quotationType: QuotationType;
    status: QuotationStatus;
    client: QuotationClientSummary;
    currencyCode: string;
    totalAmount: number;
    /**
     * Cantidad de ítems root (no incluye hijos del Servicio Integral)
     */
    itemsCount: number;
    validityDays: number;
    expiresAt?: string;
    isExpired: boolean;
    origin?: string | null;
    destination?: string | null;
    createdAt: string;
    createdBy: UserResponse;
};

export type PageOfQuotationSummary = PageMeta & {
    content: Array<QuotationSummary>;
};

/**
 * Categoría del servicio. El backend la **computa** desde el prefijo del
 * `code` (S→SERVICIO, A→ALQUILER, C→COMPLEMENTARIO, I→INTEGRAL): no es
 * columna en BD. Se expone en el response para que el frontend filtre sin
 * conocer la convención del prefijo.
 *
 * Reglas del wizard:
 * - `quotationType=TRANSPORTE` → muestra SERVICIO + COMPLEMENTARIO + INTEGRAL
 * - `quotationType=ALQUILER`   → muestra solo ALQUILER
 *
 */
export type QuotationServiceKind = 'SERVICIO' | 'ALQUILER' | 'COMPLEMENTARIO' | 'INTEGRAL';

export type QuotationServiceTypeResponse = QuotationServiceTypeRef & {
    description?: string | null;
    isActive: boolean;
};

/**
 * - `TRANSPORTE`: requiere `origin` y `destination`. Usa tipos de servicio de transporte y complementarios.
 * - `ALQUILER`: sin ruta. Solo tipos de servicio de alquiler.
 *
 */
export type QuotationType = 'TRANSPORTE' | 'ALQUILER';

/**
 * - `DRAFT`: cotización en edición, no enviada al cliente.
 * - `SENT`: ya enviada al cliente. Editable, pero queda registrado el envío.
 *
 * El estado "vencida" se calcula en runtime: `createdAt + validityDays < now()`. No se almacena.
 *
 */
export type QuotationStatus = 'DRAFT' | 'SENT';

export type QuotationServiceTypeRef = {
    id: number;
    code: string;
    name: string;
    kind: QuotationServiceKind;
};

export type QuotationStandbyCostRequest = {
    pricePerDay: number;
    includesIgv?: boolean;
};

export type QuotationStandbyCostResponse = {
    id: number;
    pricePerDay: number;
    includesIgv: boolean;
};

/**
 * Constantes runtime del módulo Quotations expuestas al frontend.
 * Los valores vienen del config del backend (`app.quotations.*`) o de
 * constantes del validator. Cacheable agresivamente (raramente cambian).
 *
 */
export type QuotationConfigResponse = {
    /**
     * IGV nacional vigente. Se persiste como snapshot en cada `quotation_items.igv_percentage` al crear.
     */
    igvPercentage: number;
    /**
     * Máximo de ítems root permitidos por cotización (hijos del Servicio Integral no cuentan).
     */
    maxRootItems: number;
    /**
     * Validez por defecto sugerida para precargar el form (el usuario puede editarla).
     */
    defaultValidityDays: number;
};

export type QuotationClientSummary = {
    id: number;
    /**
     * Razon social del cliente
     */
    name: string;
    ruc: string;
};

export type QuotationCurrencySummary = {
    id: number;
    /**
     * Codigo ISO 4217
     */
    code: string;
    symbol: string;
};

export type QuotationPaymentTermSummary = {
    id: number;
    name: string;
    days: number;
};

export type QuotationServiceTypeSummary = {
    id: number;
    code: string;
    name: string;
    /**
     * Categoria del servicio (SERVICIO/ALQUILER/COMPLEMENTARIO/INTEGRAL)
     */
    kind: string;
};

/**
 * Subset minimo del tipo de carga para embeber en items de la cotizacion.
 * Las dimensiones del catalogo (standardWeight/Length/Width/Height) NO se
 * incluyen aca: el item persiste su propio weightKg/lengthMeters/...
 * como snapshot. Los valores de referencia del catalogo siguen disponibles
 * via GET /catalogs/cargo-types/{id} si se necesitan.
 *
 */
export type QuotationCargoTypeSummary = {
    id: number;
    name: string;
};

/**
 * Item de cotización. **`unitPrice` es requerido para ítems root**; para hijos del
 * Servicio Integral debe omitirse o enviarse como 0 (en su lugar puede enviarse
 * `internalReferencePrice`).
 *
 */
export type QuotationItemRequest = {
    /**
     * Si se omite, lo asigna el backend en orden de aparición. Si la cotización tiene Integral, debe ser `1`.
     */
    itemNumber?: number | null;
    /**
     * Para ítems hijos del Integral, referencia al `itemNumber` del padre dentro del mismo request (siempre `1`).
     */
    parentItemNumber?: number | null;
    serviceTypeId: number;
    cargoTypeId?: number | null;
    observations?: string | null;
    weightKg?: number | null;
    lengthMeters?: number | null;
    widthMeters?: number | null;
    heightMeters?: number | null;
    quantity: number;
    /**
     * Requerido para ítems root. Para hijos del Integral debe omitirse o ser 0.
     */
    unitPrice?: number | null;
    /**
     * Solo válido para hijos del Integral. Opcional. NO se muestra en el PDF.
     */
    internalReferencePrice?: number | null;
    /**
     * Solo válido si `serviceTypeId` corresponde a SEG.
     */
    insuredAmount?: number | null;
    standby?: QuotationStandbyCostRequest;
};

/**
 * Ítem de cotización. Puede ser **root** (sin `parentItemId`) o **hijo del Servicio
 * Integral** (con `parentItemId` apuntando al padre).
 *
 * **Pricing según tipo:**
 * - Ítems root: `unitPrice` es el precio que paga el cliente, IGV calculado al 18%.
 * - Hijos del Integral: `unitPrice` no aplica (siempre 0); usan `internalReferencePrice`
 * opcional, que es referencia histórica interna y NO se muestra en el PDF al cliente.
 * La suma de referencias de hijos puede exceder el precio del padre (es el descuento
 * implícito del paquete Integral).
 *
 */
export type QuotationItemResponse = {
    id: number;
    /**
     * NULL para ítems root. Set para ítems hijos del Servicio Integral.
     */
    parentItemId?: number | null;
    itemNumber: number;
    serviceType: QuotationServiceTypeSummary;
    cargoType?: QuotationCargoTypeSummary;
    observations?: string | null;
    weightKg?: number | null;
    lengthMeters?: number | null;
    widthMeters?: number | null;
    heightMeters?: number | null;
    quantity: number;
    /**
     * Precio unitario que paga el cliente. Aplica solo para ítems root. En hijos del Integral siempre es 0 (usar `internalReferencePrice`).
     */
    unitPrice?: number;
    /**
     * Precio interno de referencia. Solo aplica para ítems hijos del Servicio Integral. NO se muestra en el PDF al cliente. Opcional.
     */
    internalReferencePrice?: number | null;
    igvPercentage: number;
    /**
     * `unitPrice * quantity` para root; 0 para hijos del Integral (no entran al total de la cotización).
     */
    subtotal: number;
    /**
     * Solo aplica para ítems de tipo Seguro de Carga (SEG).
     */
    insuredAmount?: number | null;
    standby?: QuotationStandbyCostResponse;
    /**
     * Ítems hijos (presente solo en ítems padre del Servicio Integral).
     */
    children?: Array<QuotationItemResponse>;
};

/**
 * ## Reglas de negocio (validadas por backend)
 *
 * - **Máximo 5 ítems root** (los hijos del Servicio Integral no cuentan).
 * - **Servicio Integral**: si la cotización tiene un ítem con `serviceType.code='INT'`:
 * - debe ser el primer ítem (`itemNumber=1`),
 * - debe tener al menos **2 ítems hijos** (referenciados vía `parentItemNumber=1`),
 * - los hijos deben incluir al menos **1 servicio de tipo TRANSPORTE (kind=S)** y
 * al menos **1 servicio de tipo COMPLEMENTARIO (kind=C)**,
 * - solo puede haber un Integral por cotización.
 * - **Origen/destino**: requeridos si `quotationType=TRANSPORTE`, ignorados si `ALQUILER`.
 * - **`contactName`**: snapshot editable. Se precarga desde `client.contactName` en el
 * formulario, pero el usuario puede editarlo. Lo que se guarda es el valor final del
 * formulario, congelado al momento de crear/editar la cotización.
 * - **Anti-duplicado**: el backend rechaza con `409 QUO-002` si llega un POST con
 * mismo `clientId` + mismo set de `serviceTypeId`s + mismo usuario creador dentro
 * de los últimos 30 segundos (protección anti doble-click backend-side).
 *
 */
export type QuotationRequest = {
    quotationType: QuotationType;
    clientId: number;
    /**
     * Obligatorio — la cotización siempre se dirige a alguien. Snapshot al momento de cotizar (se precarga del cliente, el usuario puede editarlo, queda congelado).
     */
    contactName: string;
    /**
     * Snapshot editable del telefono de contacto (9 digitos numericos). Se precarga del cliente y queda congelado en la cotización.
     */
    contactPhone?: string | null;
    currencyId: number;
    paymentTermId?: number | null;
    tentativeServiceDate?: string | null;
    validityDays: number;
    /**
     * Requerido si `quotationType=TRANSPORTE`. Validado por backend.
     */
    origin?: string | null;
    /**
     * Requerido si `quotationType=TRANSPORTE`. Validado por backend.
     */
    destination?: string | null;
    /**
     * Lista plana de ítems root e hijos. Los hijos referencian al padre vía `parentItemNumber`. Máximo 5 ítems root (validado por backend).
     */
    items: Array<QuotationItemRequest>;
};

export type QuotationResponse = {
    id: number;
    code: string;
    quotationType: QuotationType;
    status: QuotationStatus;
    client: QuotationClientSummary;
    /**
     * Snapshot del contacto al momento de cotizar (queda fijo aunque cambie el cliente master).
     */
    contactName?: string | null;
    /**
     * Snapshot del telefono de contacto al momento de cotizar (9 digitos). Queda fijo aunque cambie el cliente master.
     */
    contactPhone?: string | null;
    currency: QuotationCurrencySummary;
    paymentTerm?: QuotationPaymentTermSummary;
    tentativeServiceDate?: string | null;
    validityDays: number;
    /**
     * createdAt + validityDays (computado)
     */
    expiresAt: string;
    /**
     * now() > expiresAt
     */
    isExpired: boolean;
    origin?: string | null;
    destination?: string | null;
    /**
     * Suma de items.subtotal
     */
    totalSubtotal: number;
    /**
     * IGV total
     */
    totalIgv: number;
    /**
     * Total = subtotal + IGV
     */
    totalAmount: number;
    items: Array<QuotationItemResponse>;
    createdBy: UserResponse;
    updatedBy: UserResponse;
    createdAt: string;
    /**
     * Source de la versión para optimistic locking (mismo valor que el header ETag).
     */
    updatedAt: string;
};

/**
 * Página (base 0)
 */
export type Page = number;

/**
 * Tamaño de página (máx. 100)
 */
export type Size = number;

export type IdLong = number;

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Solicitud inválida (campos faltantes o mal formados)
     */
    400: Problem;
    /**
     * Credenciales inválidas o usuario inactivo
     */
    401: Problem;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login exitoso
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Refresh token inválido o expirado
     */
    401: Problem;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Token renovado
     */
    200: LoginResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validación de contraseña fallida o contraseña actual incorrecta
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Contraseña actualizada
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * El usuario del token ya no existe
     */
    404: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListCargoTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Búsqueda libre por nombre (substring case-insensitive; ranking por similarity). Mínimo 3 caracteres. Para no filtrar, omitir el parámetro.
         */
        q?: string;
        isActive?: boolean;
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
    };
    url: '/cargo-types';
};

export type ListCargoTypesErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListCargoTypesError = ListCargoTypesErrors[keyof ListCargoTypesErrors];

export type ListCargoTypesResponses = {
    /**
     * OK
     */
    200: PageOfCargoType;
};

export type ListCargoTypesResponse = ListCargoTypesResponses[keyof ListCargoTypesResponses];

export type CreateCargoTypeData = {
    body: CargoTypeRequest;
    path?: never;
    query?: never;
    url: '/cargo-types';
};

export type CreateCargoTypeErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateCargoTypeError = CreateCargoTypeErrors[keyof CreateCargoTypeErrors];

export type CreateCargoTypeResponses = {
    /**
     * Creado
     */
    201: CargoTypeResponse;
};

export type CreateCargoTypeResponse = CreateCargoTypeResponses[keyof CreateCargoTypeResponses];

export type ListCurrenciesData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/currencies';
};

export type ListCurrenciesResponses = {
    /**
     * OK
     */
    200: Array<CurrencyResponse>;
};

export type ListCurrenciesResponse = ListCurrenciesResponses[keyof ListCurrenciesResponses];

export type ListPaymentTermsData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/payment-terms';
};

export type ListPaymentTermsResponses = {
    /**
     * OK
     */
    200: Array<PaymentTermResponse>;
};

export type ListPaymentTermsResponse = ListPaymentTermsResponses[keyof ListPaymentTermsResponses];

export type ListQuotationServiceTypesData = {
    body?: never;
    path?: never;
    query?: {
        isActive?: boolean;
    };
    url: '/quotation-service-types';
};

export type ListQuotationServiceTypesResponses = {
    /**
     * OK
     */
    200: Array<QuotationServiceTypeResponse>;
};

export type ListQuotationServiceTypesResponse = ListQuotationServiceTypesResponses[keyof ListQuotationServiceTypesResponses];

export type ListClientsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Búsqueda libre por nombre o RUC (substring case-insensitive; ranking por similarity). Mínimo 3 caracteres. Para no filtrar, omitir el parámetro.
         */
        q?: string;
        isActive?: boolean;
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
    };
    url: '/clients';
};

export type ListClientsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ListClientsError = ListClientsErrors[keyof ListClientsErrors];

export type ListClientsResponses = {
    /**
     * OK
     */
    200: PageOfClient;
};

export type ListClientsResponse = ListClientsResponses[keyof ListClientsResponses];

export type CreateClientData = {
    body: ClientRequest;
    path?: never;
    query?: never;
    url: '/clients';
};

export type CreateClientErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateClientError = CreateClientErrors[keyof CreateClientErrors];

export type CreateClientResponses = {
    /**
     * Creado
     */
    201: ClientResponse;
};

export type CreateClientResponse = CreateClientResponses[keyof CreateClientResponses];

export type ListQuotationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Página (base 0)
         */
        page?: number;
        /**
         * Tamaño de página (máx. 100)
         */
        size?: number;
        /**
         * Búsqueda libre con coincidencia parcial sobre: `code`, `client.name`,
         * `client.ruc`, `origin`, `destination`. Usa pg_trgm para fuzzy matching.
         * Mínimo 3 caracteres.
         *
         */
        q?: string;
        status?: QuotationStatus;
        quotationType?: QuotationType;
        clientId?: number;
        createdById?: number;
        currencyId?: number;
        /**
         * Filtra cotizaciones que tengan al menos un ítem (root o hijo) con este cargo type
         */
        cargoTypeId?: number;
        /**
         * Filtra cotizaciones que tengan al menos un ítem (root o hijo) con este service type
         */
        serviceTypeId?: number;
        /**
         * Filtro por `createdAt` desde (ISO date, inclusivo). Interpretado en zona horaria de Lima (UTC-5).
         */
        dateFrom?: string;
        /**
         * Filtro por `createdAt` hasta (ISO date, inclusivo del día completo). Interpretado en zona horaria de Lima (UTC-5).
         */
        dateTo?: string;
    };
    url: '/quotations';
};

export type ListQuotationsErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type ListQuotationsError = ListQuotationsErrors[keyof ListQuotationsErrors];

export type ListQuotationsResponses = {
    /**
     * Listado paginado
     */
    200: PageOfQuotationSummary;
};

export type ListQuotationsResponse = ListQuotationsResponses[keyof ListQuotationsResponses];

export type CreateQuotationData = {
    body: QuotationRequest;
    path?: never;
    query?: never;
    url: '/quotations';
};

export type CreateQuotationErrors = {
    /**
     * Solicitud inválida (validación, formato, valores fuera de rango)
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Conflicto (recurso ya existe, restricción de unicidad violada)
     */
    409: Problem;
};

export type CreateQuotationError = CreateQuotationErrors[keyof CreateQuotationErrors];

export type CreateQuotationResponses = {
    /**
     * Cotización creada
     */
    201: QuotationResponse;
};

export type CreateQuotationResponse = CreateQuotationResponses[keyof CreateQuotationResponses];

export type GetQuotationConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/quotations/config';
};

export type GetQuotationConfigErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
};

export type GetQuotationConfigError = GetQuotationConfigErrors[keyof GetQuotationConfigErrors];

export type GetQuotationConfigResponses = {
    /**
     * Config vigente
     */
    200: QuotationConfigResponse;
};

export type GetQuotationConfigResponse = GetQuotationConfigResponses[keyof GetQuotationConfigResponses];

export type GetQuotationData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/quotations/{id}';
};

export type GetQuotationErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * Autenticado pero sin permisos para esta operación
     */
    403: Problem;
    /**
     * Recurso no encontrado
     */
    404: Problem;
};

export type GetQuotationError = GetQuotationErrors[keyof GetQuotationErrors];

export type GetQuotationResponses = {
    /**
     * OK
     */
    200: QuotationResponse;
};

export type GetQuotationResponse = GetQuotationResponses[keyof GetQuotationResponses];
