// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080/api/v1' | (string & {});
};

export type Problem = {
    /**
     * URI que identifica el tipo de error (ver catálogo de errores)
     */
    type: string;
    title: string;
    status: number;
    detail?: string | null;
    instance?: string | null;
    /**
     * Código corto del error para que el frontend pueda matchear sin parsear `detail`.
     */
    code?: string | null;
    /**
     * Identificador de la traza para correlacionar con logs.
     */
    traceId?: string | null;
    /**
     * Errores de validación por campo (presente solo cuando aplica).
     */
    errors?: Array<{
        field: string;
        message: string;
        code?: string | null;
    }>;
};

export type UserRole = 'admin' | 'sales' | 'dispatcher' | 'general_manager' | 'operations_manager';

export type LoginRequest = {
    username: string;
    password: string;
};

export type LoginResponse = {
    /**
     * JWT de acceso
     */
    token: string;
    /**
     * Token para renovar la sesión sin re-login
     */
    refreshToken?: string | null;
    expiresAt: string;
    /**
     * Segundos hasta expiración del access token
     */
    expiresIn: number;
    user: UserResponse;
};

export type RefreshRequest = {
    /**
     * JWT firmado emitido previamente por /auth/login o /auth/refresh.
     */
    refreshToken: string;
};

export type ChangePasswordRequest = {
    currentPassword: string;
    newPassword: string;
};

/**
 * Referencia mínima a un usuario (para embeber en respuestas)
 */
export type UserRef = {
    id: number;
    username: string;
    fullName: string;
    /**
     * Cargo del trabajador (ej: Ejecutiva de Ventas)
     */
    position?: string | null;
};

export type UserResponse = UserRef & {
    role: UserRole;
    isActive: boolean;
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginErrors = {
    /**
     * Solicitud inválida (campos faltantes o mal formados)
     */
    400: Problem;
    /**
     * Credenciales inválidas o usuario inactivo
     */
    401: Problem;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login exitoso
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type RefreshTokenData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Refresh token inválido o expirado
     */
    401: Problem;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
    /**
     * Token renovado
     */
    200: LoginResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validación de contraseña fallida o contraseña actual incorrecta
     */
    400: Problem;
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Contraseña actualizada
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserErrors = {
    /**
     * Token de acceso ausente, expirado o inválido
     */
    401: Problem;
    /**
     * El usuario del token ya no existe
     */
    404: Problem;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];
